CREATE TABLE IF NOT EXISTS tests (
	id 			INTEGER 	PRIMARY KEY,
	created_at 	TIMESTAMP 	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	score 		INTEGER 	NOT NULL,
	problem_id 	INTEGER 	NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
	visible_id 	INTEGER 	NOT NULL,
	orphaned 	INTEGER 	NOT NULL DEFAULT false
);
