CREATE TABLE IF NOT EXISTS problem_lists (
	id 			INTEGER 	PRIMARY KEY,
	created_at 	TIMESTAMP 	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	author_id 	INTEGER 	NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	title 		TEXT 		NOT NULL DEFAULT '',
	description	TEXT 		NOT NULL DEFAULT '',
	list 		TEXT 		NOT NULL DEFAULT ''
);
