CREATE TABLE IF NOT EXISTS attachments (
	id 			INTEGER 	PRIMARY KEY,
	created_at 	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	problem_id 	INTEGER 	NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
	visible 	INTEGER 	NOT NULL DEFAULT FALSE,

	name 		TEXT 		NOT NULL,
	data 		BLOB 		NOT NULL,
	data_size 	INTEGER 	GENERATED ALWAYS AS (length(data)) STORED
);
