package main

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/urfave/cli/v3"
)

//go:embed files/printable_contestants.typ
var printableContestantsTemplate string

var printableContestants = &cli.Command{
	Name:      "printable-contestants",
	Usage:     "Convert a teams CSV generated by contest-utils into a PDF with Typst",
	ArgsUsage: "<filename_csv> <out_filename>",
	Action: func(ctx context.Context, cmd *cli.Command) error {
		if _, err := exec.LookPath("typst"); err != nil {
			return errors.New("typst compiler not found")
		}

		if cmd.NArg() != 2 {
			return fmt.Errorf("usage: %s %s", cmd.FullName(), cmd.ArgsUsage)
		}

		inputPath := cmd.Args().Get(0)
		outputPath := cmd.Args().Get(1)

		inputData, err := os.ReadFile(inputPath)
		if err != nil {
			return fmt.Errorf("read input CSV: %w", err)
		}

		tempDir, err := os.MkdirTemp("", "kn-printable-contestants-*")
		if err != nil {
			return fmt.Errorf("create temp dir: %w", err)
		}
		defer os.RemoveAll(tempDir)

		inputCopyPath := filepath.Join(tempDir, "in.csv")
		if err := os.WriteFile(inputCopyPath, inputData, 0644); err != nil {
			return fmt.Errorf("write temporary CSV: %w", err)
		}

		templatePath := filepath.Join(tempDir, "templ.typ")
		if err := os.WriteFile(templatePath, []byte(printableContestantsTemplate), 0644); err != nil {
			return fmt.Errorf("write temporary template: %w", err)
		}

		compileCmd := exec.CommandContext(ctx, "typst", "compile", templatePath, outputPath)
		compileCmd.Stdout = os.Stdout
		compileCmd.Stderr = os.Stderr
		if err := compileCmd.Run(); err != nil {
			return fmt.Errorf("typst compile failed: %w", err)
		}

		fmt.Println("Produced file.")
		return nil
	},
}
