CREATE TABLE IF NOT EXISTS tags (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    text   NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS problem_tags (
    tag_id      bigint  NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    problem_id  bigint  NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    position    bigint  NOT NULL DEFAULT 0,
    UNIQUE (tag_id, problem_id)
);