CREATE TABLE IF NOT EXISTS contests (
	id 				bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at 		timestamptz NOT NULL DEFAULT NOW(),

	start_date 		timestamptz NOT NULL DEFAULT epoch::timestamptz,
	end_date  		timestamptz NOT NULL DEFAULT epoch::timestamptz + '3 hours'::interval, 
	duration 		interval 	GENERATED ALWAYS AS (end_date - start_date) STORED,
	
	pblist_id 		bigint 		NOT NULL REFERENCES problem_lists(id) ON DELETE RESTRICT,
);

CREATE TABLE IF NOT EXISTS contest_registrations (
	user_id 	bigint 	NOT NULL 	REFERENCES users(id) ON DELETE CASCADE,
	contest_id 	bigint	NOT NULL 	REFERENCES contests(id) ON DELETE CASCADE,
	registered_at 	timestamptz 	NOT NULL DEFAULT NOW()
);

ALTER TABLE submissions ADD COLUMN contest_id bigint REFERENCES contests(id); -- may be null
