
CREATE TYPE external_resource_type AS ENUM (
    'editorial',
    'video',
    'solution',
    'article',
    'other'
);

CREATE TABLE IF NOT EXISTS external_resources (
    id      bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    name    text        NOT NULL,
    description text    NOT NULL DEFAULT '',
    url     text        NOT NULL,
    visible boolean     NOT NULL DEFAULT false,
    accepted boolean    NOT NULL DEFAULT false,

    proposed_by bigint  REFERENCES users(id) ON DELETE SET NULL,
    type    external_resource_type NOT NULL DEFAULT 'other',
    problem_id bigint   NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    position integer     NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS problem_resources_index ON external_resources (problem_id);