BEGIN;

CREATE TABLE IF NOT EXISTS submission_files (
    id 			  	bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamptz NOT NULL DEFAULT NOW(),
    submission_id   bigint  NOT NULL REFERENCES submissions(id),
    filename        text    NOT NULL,
    data            bytea   NOT NULL,

    data_size       INTEGER NOT NULL GENERATED ALWAYS AS (length(data)) STORED
);

INSERT INTO submission_files (submission_id, filename, data)
SELECT id, code_filename, convert_to(code, 'UTF-8') FROM submissions ORDER BY id ASC;

ALTER TABLE submissions DROP COLUMN code_size;
ALTER TABLE submissions ADD COLUMN code_size INTEGER NOT NULL DEFAULT 0;
UPDATE submissions SET code_size = length(code);
ALTER TABLE submissions DROP COLUMN code;
ALTER TABLE submissions DROP COLUMN code_filename;

COMMIT;