
CREATE TABLE IF NOT EXISTS moss_submissions (
	id 			bigint 	    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz NOT NULL DEFAULT NOW(),
    
    contest_id  bigint      NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    problem_id  bigint      NOT NULL REFERENCES problems(id) ON DELETE CASCADE,

    language    text NOT NULL,

    url         text        NOT NULL,
    subcount    integer     NOT NULL
);
