import tailwindcss from "@tailwindcss/vite";
import {defineConfig, type UserConfig} from "vite";

// Templates call `bundled.*` / `vendored.*` from inline classic scripts, so each JS
// bundle has to stay an IIFE exposing a global. Rollup only emits IIFE for a single
// entry, and lib mode (the only way to keep the entry's exports) does not do CSS
// code splitting, so the stylesheets get their own multi-entry build.
// Hence: one build per BUNDLE, each with its own manifest.
const bundles: Record<string, UserConfig["build"]> = {
	bundled: {lib: {entry: "app.ts", formats: ["iife"], name: "bundled"}},
	vendored: {lib: {entry: "vendored.ts", formats: ["iife"], name: "vendored"}},
	// chroma.css is generated by `go generate ./web` into this directory.
	css: {
		rollupOptions: {
			input: ["chroma.css", "vendor.css", "tailwind.css"],
		}
	},
};

const bundle = process.env.BUNDLE ?? "bundled";
if (!(bundle in bundles)) throw new Error(`unknown BUNDLE=${bundle}`);

export default defineConfig({
	plugins: [tailwindcss()],
	// Everything is served under /static, which is what url() references inside the CSS
	// get prefixed with. Output paths stay relative to outDir, so the manifest is
	// unaffected and Go still joins "/static/" onto what it reads from there.
	base: "/static/",
	build: {
		outDir: "../static",
		emptyOutDir: false,
		// The Go handler serves everything under static/misc as immutable.
		assetsDir: "misc",
		// go:embed skips dot-directories, so keep the manifest out of .vite/
		manifest: `manifest.${bundle}.json`,
		sourcemap: true,
		target: "baseline-widely-available",
		// lib mode ignores assetsDir, so spell the paths out
		rollupOptions: {
			output: {
				entryFileNames: "misc/[name]-[hash].js",
				assetFileNames: "misc/[name]-[hash][extname]",
			},
		},
		...bundles[bundle],
	},
});
