// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package proposer

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/KiloProjects/kilonova"

func CreateProblemList(parentList *kilonova.ProblemList) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"cr_pblist_form\"><label class=\"block my-2\"><span class=\"form-label\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TC("name").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, ":</span> <input id=\"cr_pblist_title\" type=\"text\" class=\"form-input\" required></label> <label class=\"block my-2\"><span class=\"form-label\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TC("desc").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ": </span> <textarea id=\"cr_pblist_desc_tarea\" class=\"hidden\"></textarea></label> <label class=\"block my-2\"><span class=\"form-label\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TC("sublist_label").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ":</span> <input type=\"text\" id=\"cr_pblist_sublists\" class=\"form-input\" pattern=\"([0-9]+,?)+\"></label> <label class=\"block my-2\"><span class=\"form-label\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TC("pbs").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, ":</span> <input id=\"cr_pblist_pbs\" type=\"text\" class=\"form-input\" pattern=\"([0-9]+,?)+\"></label> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if parentList != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<input id=\"cr_pblist_parent_id\" type=\"hidden\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(parentList.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/proposer/create_pblist.templ`, Line: 36, Col: 70}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<label class=\"block my-2\"><span class=\"form-label\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = TC("list_parent_id").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, ":</span> <input id=\"cr_pblist_parent_id\" type=\"number\" class=\"form-input\"></label>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"block my-2\"><label class=\"inline-flex items-center text-lg\"><input class=\"form-checkbox\" name=\"sidebar_hidable\" id=\"cr_sidebar_hidable\" type=\"checkbox\"> <span class=\"ml-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TC("sidebar_hidable").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</span></label></div><button type=\"submit\" class=\"btn btn-blue\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TC("button.create").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</button></form><script>\n    var cr_pblist_cm = new vendored.KNEditor({\n    \ttextArea: document.getElementById(\"cr_pblist_desc_tarea\"),\n    \tlanguage: \"md\",\n    \tdynamicSize: true,\n    })\n\n    async function createProblemList(e) {\n    \te.preventDefault()\n\n        const parentID = parseInt(document.getElementById(\"cr_pblist_parent_id\").value);\n\n    \tlet data = {\n    \t\ttitle: document.getElementById(\"cr_pblist_title\").value,\n    \t\tdescription: cr_pblist_cm.getText(),\n    \t\tids: bundled.stringIntToNumber(document.getElementById(\"cr_pblist_pbs\").value.split(',')),\n            sublists: bundled.stringIntToNumber(document.getElementById(\"cr_pblist_sublists\").value.split(',')),\n            sidebar_hidable: document.getElementById(\"cr_sidebar_hidable\").checked,\n        };\n\n        if(!isNaN(parentID)) {\n            data.parent_id = parentID\n        }\n\n    \tlet res = await bundled.bodyCall(\"/problemList/create\", data)\n    \tif(res.status === \"success\") {\n            if(res.data.nested) {\n                // go to parent instead\n                window.location.assign(`/problem_lists/${parentID}`);\n                return\n            }\n    \t\twindow.location.assign(`/problem_lists/${res.data.id}`);\n    \t\treturn\n    \t}\n    \tbundled.apiToast(res)\n    }\n\n    document.getElementById(\"cr_pblist_form\").addEventListener(\"submit\", createProblemList)\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
